### ISSUE TITLE
sdk uncaught third Error 

### ISSUE THREAD

**Issue by LiweiDong** [afishhhhh/mp-request#1]
`module "npm/weapp.request/index.js" is not defined`

**Comment by LiweiDong** [comment]
require('./src/index') 改成 require('./dist/index') 就行了

**Comment by afishhhhh** [comment]
> require('./src/index') 改成 require('./dist/index') 就行了

@LiweiDong 你是怎么安装的？这个require的确是写错了，但是我试了下没有影响使用
